### ISSUE TITLE
B02コンポーネントホワイトルールで意図しないエラー内容になる

### ISSUE THREAD

**Issue by gatosyocora** [VitDeck/VitDeck-for-vket#32]
ExportBooth時に表示されるVitDeckに元から同封されているB02_ComponentWhitelistRuleのエラーメッセージが以下のようになっている。
![image](https://user-images.githubusercontent.com/18584961/72250584-3e0b7800-363f-11ea-870f-4c554f2e40df.png)
すべての内容で「BoothRangeIndicatorは使用可能なコンポーネントリストに登録されていません。」と表示されているがBoothRangeIndicatorは該当オブジェクトにはアタッチされていない

**Comment by sokuhatiku** [comment]
BoothRangeIndicatorはBoothBoundsRuleで使用しているブース範囲の可視化オブジェクトで、hideflags設定によって見えない、セーブされない設定になっています。
ExportBooth時には設定を弄らない限りVket向けに開発したものとは別のルールが設定されているはずなので、その為に例外設定されておらずエラーになってしまうのだと思います。（まだExport Booth周りは弄ってません。）

**Comment by sokuhatiku** [comment]
ExportBoothに関してはVketTools側からの呼び出しになると思うので、VketTools側の人とどう提携するのか打ち合わせた上で作業を行う予定でいます。

**Comment by sokuhatiku** [comment]
既に対応済みの為クローズ
