### ISSUE TITLE
Load Templateで作成されるシーンの構成をどうするか

### ISSUE THREAD

**Issue by gatosyocora** [VitDeck/VitDeck-for-vket#33]
LoadTemplateを実行すると以下のようなシーンが作成される
![image](https://user-images.githubusercontent.com/18584961/72251128-8d05dd00-3640-11ea-9a94-5cb3c2a16331.png)

入稿されるデータが
* シーンファイル名がidのみ
* ルートオブジェクト名がid
* ルートオブジェクト以下に空オブジェクトでDynamicとStatic

のようになる場合は、
Template自体もこのように構成されていたほうが良さそう

~ただ今回はワールドによって違う構成になりそうな気もします~

**Comment by gatosyocora** [comment]
現状のテンプレートで作成した場合、シーンファイル名がフォルダ名と異なるため、現状の入稿シーンを探すルールでシーンが見つからないエラーが出ます。
![image](https://user-images.githubusercontent.com/18584961/72252433-94c68100-3642-11ea-901e-f5f8c9057003.png)

また、ルートオブジェクト名も異なるため、入稿物が見つからないエラーも表示されます。
![image](https://user-images.githubusercontent.com/18584961/72252546-cc352d80-3642-11ea-819a-f18baaf5814a.png)

**Comment by sokuhatiku** [comment]
テンプレートの方も（ExportBoothと同じく）手を加えていない状態なのでエラーが出てしまいます。ただ、ルートフォルダの命名規則などは差し替えが可能なので、エラーが出ない状態に修正することは可能です。

**Comment by gatosyocora** [comment]
作成してみていますが、以前話にあったようにワールドごとにBoundsのサイズが違うので
* ワールドや合同ブースの可否の分だけtemplateを用意するのか
* テンプレートから作成する際にScaleLimitVisualizerの値を変更させるのか
悩ましいところです。
![image](https://user-images.githubusercontent.com/18584961/72528995-b1b3bc00-38af-11ea-8d5d-91310c1acf59.png)

**Comment by sokuhatiku** [comment]
TemplateLoaderの現行の仕組みをそのまま使うならテンプレートを数だけ用意する形になるでしょうか。
今回はブース雛形が多く配布されているので、こちらから提供するテンプレートは、入稿ルール及びライティング環境をセットアップした最低限のものが丁度いいのかな？と思っています。
