### ISSUE TITLE
以下のようなエラーメッセージが望ましい「出展者がどう対処したら良いかがわかる」「エラーの内容が出展者目線である」

### ISSUE THREAD

**Issue by mizunanana** [VitDeck/VitDeck-for-vket#47]
### 現状のエラーメッセージ一覧
- https://docs.google.com/spreadsheets/d/1DiiYFbTNYoC_KIBPLMfLFfHMRBhuZz6JXBFW-0U1tlo/edit#gid=0

### 改善例
- 入稿フォルダに含まれるファイルサイズの合計が52428800バイトを超えています。
    - 修正方法がほしい
    - 50メガバイトを超えないように不要ファイル削除等を行ってください。→参照URL
- 許可されていないPrefabを使用しないこと
    - 許可されているPrefabとは何か？がわからない
    - 入稿フォルダーに含まれているPrefabおよび公式Prefab以外のPrefabは使用できません
- VRC_Stationの使用は許可されていません。
    - VRC_Stationコンポーネントの使用は公式Prefabを使う場合のみ許可されています。公式Prefabを使用してください。

**Comment by sokuhatiku** [comment]
VitDeck側のメッセージ一覧のシートも貼っておきます。
https://docs.google.com/spreadsheets/d/1eMpJxkUNAksvBNiBnBYnqp-oJBdhoVWwuchUo2RX8uU/edit#gid=0

**Comment by sokuhatiku** [comment]
> 入稿フォルダに含まれるファイルサイズの合計が52428800バイトを超えています。

解決方法及びリンクのMessageID追加、メッセージのテキストも作成する
URLや解決方法のMessageIDを用意していないルールが多くあるが、基本全てMessageIDを振り、使わない個所は空白にするのがいいかも？

> 許可されていないPrefabを使用しないこと
> VRC_Stationの使用は許可されていません。

メッセージのみ修正

**Comment by sokuhatiku** [comment]
#56 もついでに対応してしまう

**Comment by sokuhatiku** [comment]
> 許可されていないPrefabを使用しないこと

1c107bb76d25cb48a1fb8c1292198b1bfbde0112 で対応  

> VRC_Stationの使用は許可されていません。

55f1787863acb3a2b5a1960e1b778490e0fdeedc で対応

**Comment by sokuhatiku** [comment]
汎用的なバリデーションを利用した結果Prefab経由で利用できるコンポーネントとそうでないコンポーネントでメッセージに差分を持たせることが出来なかった為、SolutionおよびSolutionURLを用意して両パターンに対応できるようにしました。
