### ISSUE TITLE
配置班がツールで対処していた内容を先にチェックする

### ISSUE THREAD

**Issue by mizunanana** [VitDeck/VitDeck-for-vket#49]
- Lightmap StaticなのにLightmap UVが無いオブジェクトをチェック
- Occluder Staticを禁止にする

**Comment by sokuhatiku** [comment]
Lightmap UVが無いオブジェクトの検出方法を調べる必要あり

**Comment by sokuhatiku** [comment]
Occluder Static禁止に関しては 9a93b62a5f73b8610d1b8a5581f7dc8947cc99a6 で対処しました。

**Comment by sokuhatiku** [comment]
Lightmap Staticを有効にしたメッシュのuv2チェックに関しても 0e26bc7ff3cf73392833b4947b97f84039e3c551 で対応しました。
