### ISSUE TITLE
Missing Prefabで入稿されるのをエラーチェックで防止する

### ISSUE THREAD

**Issue by mizunanana** [VitDeck/VitDeck-for-vket#52]
- Prefabファイルが入稿フォルダー外にあってもチェックが通ってしまう？

**Comment by sokuhatiku** [comment]
Prefab検出ロジックが上手く動いていないかもしれないので調べる必要あり

**Comment by sokuhatiku** [comment]
Prefabの入稿フォルダ外チェックがうまく動作していなかったのを確認したため、 ee5c80a814e565f576147d89b8833594736c46a3 で対処しました。
