### ISSUE TITLE
公式プレハブを使っているのにその部分が使用不可コンポーネントでエラーになる現象が多発している。要原因調査

### ISSUE THREAD

**Issue by mizunanana** [VitDeck/VitDeck-for-vket#53]
- →これ、プレファブをUnpackしてると起きたように思います

**Comment by sokuhatiku** [comment]
PrefabのUnpackの阻止及び検出はまだ方法が見つかっていないので対応が難しい

**Comment by esperecyan** [comment]
Vケット4のときに注意が挙がっていましたが、他のプレハブインスタンスの子孫に公式プレハブインスタンスが存在すると、エラーになるようです。

**Comment by sokuhatiku** [comment]
@esperecyan PickupObjectSyncが入れ子になってはいけないルールがあったかと思うのですが、それ以外でもエラーが出るという事でしょうか？

**Comment by esperecyan** [comment]
公式プレハブでないプレハブインスタンスにAvatarPedestalの公式プレハブインスタンスを入れて確認しました。2つのプレハブインスタンスがヒエラルキー上で入れ子関係になっていると、先祖側のプレハブインスタンスのみチェックされて、子孫側のプレハブインスタンスは展開されたものとして扱われているような挙動をします。

**Comment by esperecyan** [comment]
先祖側のプレハブへ、子孫側の公式プレハブインスタンスの追加が適用されていない状態だと、エラーにはならないみたいです。

**Comment by sokuhatiku** [comment]
@esperecyan ありがとうございます。確認できたため 902f8dde6f91e5fafef2ab5c5cb93a0ab4b5f4bb にて修正を行いました。
ただしNested Prefabに関してははまだ挙動を理解しきれていない為、他にバグが含まれているかもしれません。

**Comment by esperecyan** [comment]
対応ありがとうございます。vkettools側に取り込みました。
