### ISSUE TITLE
MeshBakerを使用した場合にMeshBakerのcsファイルを入稿フォルダーに入れるようにエラーメッセージが表示されてしまう。

### ISSUE THREAD

**Issue by mizunanana** [VitDeck/VitDeck-for-vket#55]
- シーン上で削除したオブジェクトも何らかの参照が残っている？

**Comment by sokuhatiku** [comment]
とりあえずMeshBakerを触ってみているのですが、MeshBakerで圧縮されたメッシュはシーンファイルに埋め込まれ、Prefab化して外に出すと参照が切れる模様。 #52 に関係ある？

**Comment by sokuhatiku** [comment]
普通に使ってみただけではエラーメッセージは出ず

**Comment by joniburn** [comment]
Texture BakerのCreate Empty Assets For Combined Materialを実行した際に作成される.assetファイルが入稿フォルダー内にあると、`アセットAssets/MeshBaker/scripts/MB2_TextureBakeResults.csが入稿フォルダ内に含まれていません。`エラーになるようです。
この.assetファイルはベイク完了後は不要のはずなので、削除すればエラーは発生しなくなります。
関連: #58

**Comment by sokuhatiku** [comment]
こちらに関しては #58 の対応で対処すべきアセットが明確になれば問題無さそうでしょうか？

**Comment by joniburn** [comment]
そうですね、それで一旦クローズで良いと思います
