### ISSUE TITLE
ブースチェックのファイル容量制限エラーがbyte単位で見にくいので、MB単位にしたい

### ISSUE THREAD

**Issue by mizunanana** [VitDeck/VitDeck-for-vket#56]

**Comment by sokuhatiku** [comment]
実装はそれほど難しくないはず
https://stackoverflow.com/questions/281640/how-do-i-get-a-human-readable-file-size-in-bytes-abbreviation-using-net

**Comment by sokuhatiku** [comment]
fb581c91301bc36327b85e8b0624c5a4045aa22b で読みやすい値を返すUtilityを作成しました。
