### ISSUE TITLE
入稿フォルダに含まれていないエラーの発生元を表示してほしい

### ISSUE THREAD

**Issue by joniburn** [VitDeck/VitDeck-for-vket#58]
## 概要

「アセット○○が入稿フォルダ内に含まれていません。」エラーについて、入稿フォルダー内のアセットが入稿フォルダー外のアセットに依存している場合に発生することがある。この場合、「アセット△△が、入稿フォルダに含まれていないアセット○○に依存しています。」と表示してほしい。アセット△△はシーンで使用しておらず、削除することでエラーを解決できる場合がある。

## 実際におきたこと

VRMのモデルをシーンに配置しようとしたが、UniVRMの.csを入稿フォルダーに含めるように言われた。
1. UniVRMをインポートした。( `UniVRM-0.60.0_2b9d.unitypackage` を使用)
2. vrmファイルを入稿フォルダーにコピーした。以下が作成される。
    * (VRMファイル名).Avatar フォルダー
    * (VRMファイル名).AvatarDescription フォルダー
    * (VRMファイル名).BlendShapes フォルダー
    * (VRMファイル名).Materials フォルダー
    * (VRMファイル名).Meshes フォルダー
    * (VRMファイル名).MetaObject フォルダー
    * (VRMファイル名).Textures フォルダー
    * (VRMファイル名).vrm ファイル(ドラッグアンドドロップしたファイル)
    * (VRMファイル名).prefab ファイル
3. prefabをシーンに配置し、Unpack Prefab Completelyを実行した。
4. VRM関連のコンポーネントをすべてRemove Componentした。AnimatorとSkinnedMeshRendererのみ残った。
5. この状態でブースチェックを実行すると、`アセットAssets/VRM/UniVRM/Scripts/Meta/VRMMeta.csが入稿フォルダ内に含まれていません。`のようなエラーが出た。添付ファイル参照。
6. 2で作成されたファイルのうち、以下を削除するとエラーが解消された。エラーメッセージでこれらのファイルがフォルダ外のファイルに依存していることが表示されると原因特定に役立つ。
    * (VRMファイル名).AvatarDescription フォルダー
    * (VRMファイル名).BlendShapes フォルダー
    * (VRMファイル名).MetaObject フォルダー
    * (VRMファイル名).prefab ファイル

[添付ファイル：Untitled-1.txt](https://github.com/VitDeck/VitDeck-for-vket/files/5259983/Untitled-1.txt)

**Comment by sokuhatiku** [comment]
検証対象アセットの捜索時に、全参照を辿って辞書を作成しているので、それを引っ張ってくれば目的は達成できそうです。

**Comment by sokuhatiku** [comment]
ee5c80a814e565f576147d89b8833594736c46a3 で対応しました。
