### ISSUE TITLE
範囲外はみ出しのBoundsを表示してほしい

### ISSUE THREAD

**Issue by joniburn** [VitDeck/VitDeck-for-vket#59]
現在は左のようにはみ出し範囲を表示しているが、右のような表示にできるとわかりやすい。

オブジェクトを傾けた際にBoundsの角がはみ出ているケースが多く、見た目はみ出ていないのにはみ出ていると言われてしまい原因が分かりづらい。特にMeshRendererはBoundsが表示されないため。

![image](https://user-images.githubusercontent.com/1238086/94428662-0f80fd80-01cc-11eb-9a1b-17c948b80eee.png)

参考までに、MeshRendererのBoundsを表示するコード
https://github.com/joniburn/ShowMeshRendererBounds/blob/master/ShowMeshRendererBounds.cs

**Comment by sokuhatiku** [comment]
現在の描画の仕組みでは図右のようなBox以外の表示は難しいのと、極端にはみだしが小さい場合に赤い表示の面積が少なくなり見逃してしまう可能性がある為、赤表示は可能であれば今のままにしておきたいです。メッシュのBoudsが表示されていれば見た目がはみ出ていないように見える問題は解決できるでしょうか？

**Comment by joniburn** [comment]
はみ出し表示の赤と実際のBoundsが重なっても視認できる感じであればそれでも問題ないと思います。

**Comment by sokuhatiku** [comment]
bfd6c872af9ed9ccfb8ce32ef25fb7bddf64d9ca でメッシュに対して以下の画像のような表示を行うように修正を行いました。内側の直方体がローカルのboundsです。
![image](https://user-images.githubusercontent.com/7193342/96361836-1d3ef880-1164-11eb-80ca-2a51731b7e26.png)
![image](https://user-images.githubusercontent.com/7193342/96361847-2cbe4180-1164-11eb-8c2a-a0d9e4115eb7.png)
