### ISSUE TITLE
マテリアル数制限エラーのメッセージがマテリアル数分だけ出力される

### ISSUE THREAD

**Issue by joniburn** [VitDeck/VitDeck-for-vket#62]
マテリアル数20個の制限に対して23個ある場合、 `Materialの使用数が20個を超えています。` が23個出力されてしまう。1個で十分。

**Comment by sokuhatiku** [comment]
こちら最初に設定した背景としては、削除するマテリアルを選択する為に一つ一つ確認できた方が良い、という判断で全て表示させるようにしていました。ただ大量のエラー表示を出して混乱させるのは本意ではないので、一個にまとめてみようと思います。

**Comment by sokuhatiku** [comment]
こちらは deb876880d40bebfef17aab8accea923b4e7e56e で対応しました。
